opentensor/developer-docs

- docs/glossary.md
- docs/whats-new-in-docs.md
https://github.com/opentensor/developer-docs/issues/113
> Overhauled the Glossary section

- docs/subnets/register-validate-mine.md
https://github.com/opentensor/developer-docs/issues/135
> Fixing a nit

- docs/subnets/subnet-hyperparameters.md
Fixing a couple of typos and one instance of two (2) blank spaces between words.
> Update subnet-hyperparameters.md (typo correction)

- docs/emissions.md
- docs/root-network.md
- docs/subnets/create-a-subnet.md
- docs/subnets/subnet-hyperparameters.md
- docs/whats-new-in-docs.md
- sidebars.js
In addition, added a new doc called "Root Network".
> Added docs for set_adjustment_alpha, min TAO for setting weights and a new subnet starts with zero emissions

- docs/getting-started/installation.md
- docs/subnets/working-with-subnets.md
https://github.com/opentensor/developer-docs/issues/156
> Reorged and clarified installation steps

- docs/subnet-pages/subnet-8.md
Subnet 8 has updated their subnet model.
- Updated `docs/subnet-pages/subnet-8.md`
> Update subnet 8

- docs/subnets/create-a-subnet.md
- docs/whats-new-in-docs.md
> Adding a note on subnet deregistration

- yarn.lock
Revert "Updating to docusaurus 3.2"
This reverts commit 6e4a7c0510b4e61d076dd1043bb24be63d4a2d9b.
> Reverting back to docusaurus 3.1 to see if the last edit bug disappears

- docs/index.md
- docusaurus.config.js
- src/theme/DocItem/Content/styles.module.css
And also changing python api to bittensor api.
> Removing top nav items, reducing top level h1 font size

- docs/subnet-pages/subnet-2.md
Hi OTF!
Updated the details of SN2 to match it's new purpose.
Happy to make any changes!
> Updated new details of SN2

- docs/learn/bittensor-building-blocks.md
https://github.com/opentensor/developer-docs/issues/205
> Fixing a line, per issue 205

- docs/learn/anatomy-of-incentive-mechanism.md
> fix:broken-links-to-SN1-docs

- src/css/style.css
- src/theme/DocBreadcrumbs/Items/Home/index.js
- src/theme/DocBreadcrumbs/Items/Home/styles.module.css
- src/theme/DocBreadcrumbs/index.js
- src/theme/DocBreadcrumbs/styles.module.css
- src/theme/DocItem/Content/index.js
- src/theme/DocItem/Content/styles.module.css
> Sidebar is now properly stickied

- package.json
- src/theme/DocItem/Content/index.js
- yarn.lock
> Upgraded to Docusaurus 3.2.1

- docs/btcli.md
> Removed set_delegate_take subcommand as it was prematurely documented

- docs/emissions.md
- docs/glossary.md
- docs/questions-and-answers.md
- docs/root-network.md
- docs/subnets/create-a-subnet.md
https://github.com/opentensor/developer-docs/issues/241
> Revised docs to remove the number 32 referring to subnets

- docs/subtensor-nodes/using-source.md
cc: @distributedstatemachine @sam0x17
> Fix lite node flags

- docs/bittensor-rel-notes.md
- docs/chain-rel-notes.md
- docs/subnets/commit-reveal.md
- docs/whats-new-in-docs.md
> Bittensor 7.1.0 and mainchain release notes

- docs/btcli.md
https://github.com/opentensor/developer-docs/issues/269
cc: @Jackalgirl
> Adding doc for btcli swap_hotkey

- docs/chain-rel-notes.md
- docs/subnets/commit-reveal.md
- docs/subnets/consensus-based-weights.md
- docs/whats-new-in-docs.md
- sidebars.js
New doc for the consensus-based weights feature. See the Discord thread: https://discord.com/channels/799672011265015819/1252704561781542922
> New doc for consensus-based weights, plus tweaks to commit reveal doc

- docs/learn/anatomy-of-incentive-mechanism.md
Fixing minor typo in anatomy-of-incentive-mechanism.md
> Fixing minor typo

- docs/subtensor-nodes/using-source.md
- Updated the Linux installation commands to include all necessary packages in a more concise manner.
- Added a command for installing the necessary packages on macOS using Homebrew.
> Update Linux installation commands and add macOS installation command

- docs/subtensor-nodes/using-docker.md
Add a command to clean up the Docker environment by removing all unused data
This includes stopped containers, unused networks, unused images, build cache, and unused volumes.
> Add command to clean up Docker environment by removing all unused data

- docs/getting-started/installation.md
pip3 install bittensor --no-deps
INSTRUCTIONS SHOULD REMOVE --no-deps 
https://discord.com/channels/799672011265015819/1258875961785712680
[Typos.pdf](https://github.com/user-attachments/files/16167866/Typos.pdf)
> Removed flag `--no-deps` from install bittensor

- WRITING-STYLE-GUIDE.md
> Resetting the name to Watchmaker

- docs/errors-and-troubleshooting.md
> Troubleshooting SSL Certifaction error 

- docs/subnets/consensus-based-weights.md
- docs/subnets/register-validate-mine.md
Small typo fix on the register-validate-mine page
> Some changes on the consensus-based-weights page

- docs/subtensor-nodes/using-source.md
Update subtensor build instructions.
> chore: update subtensor build instructions

- docs/subtensor-nodes/using-source.md
Reverts opentensor/developer-docs#370
> Revert "chore: update subtensor build instructions"

- docs/getting-started/installation.md
- docs/getting-started/wallets.md
Fixes a typo and updates btcli `--use_password` arg to the new `--use-password` format.
> Light changes

- docs/subtensor-nodes/using-source.md
Updating this doc as per the change made in https://github.com/opentensor/subtensor/pull/1025
> Updating chain spec files path

- docs/evm-tutorials/evm-localnet-with-metamask-wallet.md
- docs/evm-tutorials/evm-mainnet-with-metamask-wallet.md
- docs/evm-tutorials/evm-testnet-with-metamask-wallet.md
- docs/evm-tutorials/index.md
- sidebars.js
- Adds a how to for connecting a metamask wallet to mainnet, to get set up for using EVM
- Corrects stale values for RPC endpoint and chain id
> add mainnet tutorial

- docs/dynamic-tao/dtao-faq.md
- docs/dynamic-tao/sdk-cheat-sheet.md
- docs/working-with-keys.md
> Quick fixes

- docs/index.md
- docs/learn/introduction.md
- docs/questions-and-answers.md
Part 1 of a transition away from certain terms:
- reward(s)
- dividends
- distribute/distribution
- earn
- recieve/send (emissions)
- subnet owner
we prefer:
- (Best) Participants *harvest* TAO (and alpha) emitted by Bittensor
- Allocation (i.e. harvest = allocation of emitted TAO/alpha)
- Credit/debit (emissions to a participant)
- Subnet Creator
> Refine language: reward -> harvest 

- docs/subtensor-nodes/subtensor-storage-query-examples.md
Brings Subtensor storage query examples up to date.
> Update Storage Query Examples

- docs/dynamic-tao/sdk-cheat-sheet.md
there is no get_netuids method in [code](https://github.com/opentensor/bittensor/blob/master/bittensor/core/subtensor.py)
> remove get_netuids

- docs/index.md
Fixed link on front page to point to FAQ.
> Fixed FAQ link on front page.

- docs/staking-and-delegation/managing-stake-sdk.md
There are some python scripts throughout the docs that don't close websocket connections as according to best practices, as described here https://github.com/opentensor/developer-docs/pull/534. 
This PR attempts to fix those.
> Fixing py scripts with `with`

- docs/btcli-permissions.md
Took an edit pass on this recently published new page.
> Copy edits for btcli permissions guide.

- docs/getting-started/wallets.md
> Copy edits and concept clarification for wallets page.

- docs/sdk/managing-subtensor-connections.md
- docs/staking-and-delegation/managing-stake-sdk.md
- docs/subnets/asyncio.md
- sidebars.js
> Best practices for handling subtensor connections in python

- docs/subnets/create-a-subnet.md
This update provides instructions on starting a subnet.  However, I'm not sure that the tip/caution information is correct.  Please provide feedback (especially with respect to staking to an inactive subnet -- whether it's possible to self-stake but not delegate stake, or not stake at all, and what the upshot is for a subnet owner).  Thanks!
> Update create-a-subnet.md to include subnet starting instructions
